language: java

jdk:
  - oraclejdk8
  - openjdk7

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: scottx611x@gmail.com
  on_success: never